import type { Metadata } from "next";
import { Inter , Roboto , Poppins, Open_Sans, Source_Sans_3 } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
// export const sourcesans = Source_Sans_3({subsets: ["latin"] , style:["normal"], variable:'--sourcesans-font'})
// export const opensans = Open_Sans({subsets: ["latin"] ,style:["normal"], variable:'--opensans-font'})
// export const roboto =Roboto({
//   weight:['400' , '700' , '500'],
//   subsets: ["latin"],
//   style:['normal'],
//   variable:'--roboto-font'
// })
export const metadata: Metadata = {
  title: "Food blogging",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
